msc:
  # Service name will be added to each message as it prefix
  publisher_name: '%env(MSC_NAME)%'
  # Put topics that you are interested in, keep symfony messenger style.
  # Example:
  #  queue:
  #    app_queue:
  #      binding_keys: ['orders.*']
  queue: