msc:
  # Service name will be added to each message as it prefix
  service_name: '%env(MSC_NAME)%'
  # Put topics that you are interested in,
  # For ex.
  #
  # binding_keys:
  #     - 'orders.*'
  #     - 'payments.*'
  binding_keys: