services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Vehis\Msc\Generator\:
    resource: '../../Generator/'

  Vehis\Msc\Message\Validator\:
    resource: '../../Message/Validator/'

  Vehis\Msc\Publisher\:
    resource: '../../Publisher/'

  Vehis\Msc\Publisher\Amqp\AmqpMessagePublisher: ~
  Vehis\Msc\Publisher\MessagePublisherInterface: '@Vehis\Msc\Publisher\Amqp\AmqpMessagePublisher'

  Vehis\Msc\Generator\RoutingKeyGenerator:
    arguments:
      $publisherName: '%msc.publisher_name%'