services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Vehis\MsC\Generator\:
    resource: '../../Generator/'

  Vehis\MsC\Publisher\:
    resource: '../../Publisher/'

  Vehis\MsC\Generator\RoutingKeyGenerator:
    arguments:
      $publisherName: '%msc.publisher_name%'