services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Vehis\Msc\Generator\:
    resource: '../../Generator/'

  Vehis\Msc\Publisher\:
    resource: '../../Publisher/'

  Vehis\Msc\Publisher\MessagePublisher:
    arguments:
      $publisherName: '%msc.publisher_name%'