name: Run PHPUnit

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t vehis-msc-test -f Dockerfile .

      - name: Run PHPUnit inside container
        run: docker run --rm vehis-msc-test vendor/bin/phpunit tests --colors=always --testdox
