name: PHPUnit

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: vehis-msc-test

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME -f Dockerfile .

      - name: Install Composer dependencies
        run: docker run --rm -v $PWD:/app -w /app $IMAGE_NAME composer install --no-interaction --prefer-dist

      - name: Run PHPUnit inside container
        run: docker run --rm -v $PWD:/app -w /app $IMAGE_NAME vendor/bin/phpunit tests --colors=always --testdox
